# Coding Practice - Day 9

## Numpy

In [3]:
# Import NumPy and print its version
import numpy as np
print(np.__version__)

1.26.4


In [27]:
# Create a 1D NumPy array containing numbers from 1 to 10
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
# Create a 2D array with 3 rows and 3 columns
array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# Create a 3D array containing two 2×2 matrices
array = np.array([[[1,2],
                   [3,4]],[
                   [5,6],
                   [7,8]]])
print(array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# Print array properties
array = np.array([[10,20,30],
                  [40,50,60]])
print("Dimensions =", array.ndim)
print("Shape =", array.shape)
print("Size =", array.size)
print("Data Type =", array.dtype)

Dimensions = 2
Shape = (2, 3)
Size = 6
Data Type = int32


In [37]:
# Create an array from 10 to 100 with step 10
array = np.arange(10,101,10)
print(array)

[ 10  20  30  40  50  60  70  80  90 100]


In [39]:
# Create an array of 20 zeros and another array of 20 ones
zeros = np.zeros(20)
ones = np.ones(20)
print("Zeros Array")
print(zeros)
print()
print("Ones Array")
print(ones)

Zeros Array
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Ones Array
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [41]:
# Create a 5×5 identity matrix
array = np.eye(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
# Create a 4×4 array filled with random integers between 1 and 100
array = np.random.randint(1,101,(4,4))
print(array)

[[21 12 37 89]
 [ 5  6 91 51]
 [12 58  4  9]
 [79 96 86 69]]


In [45]:
# Create an array containing only even numbers from 2 to 50
array = np.arange(2,51,2)
print(array)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [47]:
# Create a 3×4 matrix and print its properties
array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(array)
print("Shape =", array.shape)
print("Dimensions =", array.ndim)
print("Total Elements =", array.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape = (3, 4)
Dimensions = 2
Total Elements = 12


In [49]:
# Create two arrays and perform operations
array1 = np.array([10,20,30,40])
array2 = np.array([2,4,5,8])
print("Addition")
print(array1 + array2)
print()
print("Subtraction")
print(array1 - array2)
print()
print("Multiplication")
print(array1 * array2)
print()
print("Division")
print(array1 / array2)

Addition
[12 24 35 48]

Subtraction
[ 8 16 25 32]

Multiplication
[ 20  80 150 320]

Division
[5. 5. 6. 5.]


In [51]:
# Create an array from 1 to 100 and print numbers divisible by 7
array = np.arange(1,101)
result = array[array % 7 == 0]
print(result)

[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]


In [53]:
# Create a 5×5 random array and find statistics
array = np.random.randint(1,101,(5,5))
print(array)
print()
print("Maximum =", np.max(array))
print("Minimum =", np.min(array))
print("Mean =", np.mean(array))
print("Sum =", np.sum(array))

[[40 24 43  2  1]
 [53 58  8 98 71]
 [67 20 47 16  9]
 [28 20 45 73 61]
 [ 4 40  4 89 42]]

Maximum = 98
Minimum = 1
Mean = 38.52
Sum = 963


In [55]:
# Create an array of 30 random integers (1–100) and count even, odd and numbers greater than 50
array = np.random.randint(1,101,30)
print(array)
even = np.sum(array % 2 == 0)
odd = np.sum(array % 2 != 0)
greater = np.sum(array > 50)
print()
print("Even Numbers =", even)
print("Odd Numbers =", odd)
print("Numbers Greater Than 50 =", greater)

[53 69  8 10 31 48 29 44 26 35 71 13 96  4 13  5 79 36 43 50 31 17 73 72
 23 67 98 69 72 70]

Even Numbers = 13
Odd Numbers = 17
Numbers Greater Than 50 = 12


In [57]:
# Print First, Last and Third Element
array = np.array([10,20,30,40,50])
print("First Element =", array[0])
print("Last Element =", array[-1])
print("Third Element =", array[2])

First Element = 10
Last Element = 50
Third Element = 30


In [59]:
# Slicing a 1D Array
array = np.array([5,10,15,20,25,30])
print("First Three Elements")
print(array[:3])
print()
print("Last Three Elements")
print(array[-3:])
print()
print("Middle Four Elements")
print(array[1:5])

First Three Elements
[ 5 10 15]

Last Three Elements
[20 25 30]

Middle Four Elements
[10 15 20 25]


In [61]:
# Print Rows of a 3×3 Matrix
array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("First Row")
print(array[0])
print()
print("Second Row")
print(array[1])
print()
print("Third Row")
print(array[2])

First Row
[1 2 3]

Second Row
[4 5 6]

Third Row
[7 8 9]


In [63]:
# Print Columns of a 3×3 Matrix
array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("First Column")
print(array[:,0])
print()
print("Second Column")
print(array[:,1])
print()
print("Third Column")
print(array[:,2])

First Column
[1 4 7]

Second Column
[2 5 8]

Third Column
[3 6 9]


In [65]:
# First Two Columns and Last Two Columns
array = np.array([[1,2,3,4],
                  [5,6,7,8]])
print("First Two Columns")
print(array[:,:2])
print()
print("Last Two Columns")
print(array[:,2:])

First Two Columns
[[1 2]
 [5 6]]

Last Two Columns
[[3 4]
 [7 8]]


In [67]:
# Top-Left and Bottom-Right 2×2 Submatrix
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
print("Top Left 2x2")
print(array[:2,:2])
print()
print("Bottom Right 2x2")
print(array[2:,2:])

Top Left 2x2
[[1 2]
 [5 6]]

Bottom Right 2x2
[[11 12]
 [15 16]]


In [69]:
# Every Second, Every Third and Reverse
array = np.arange(1,21)
print("Every Second Element")
print(array[::2])
print()
print("Every Third Element")
print(array[::3])
print()
print("Reverse Array")
print(array[::-1])

Every Second Element
[ 1  3  5  7  9 11 13 15 17 19]

Every Third Element
[ 1  4  7 10 13 16 19]

Reverse Array
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [71]:
# Middle Row, Middle Column and Center Element
array = np.arange(1,26).reshape(5,5)
print(array)
print()
print("Middle Row")
print(array[2])
print()
print("Middle Column")
print(array[:,2])
print()
print("Center Element")
print(array[2,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Middle Row
[11 12 13 14 15]

Middle Column
[ 3  8 13 18 23]

Center Element
13


In [73]:
# 3D Array Indexing
array = np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[10,11,12],
                   [13,14,15],
                   [16,17,18]]])
print("First Matrix")
print(array[0])
print()
print("Second Matrix")
print(array[1])
print()
print("First Row of Second Matrix")
print(array[1,0])

First Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second Matrix
[[10 11 12]
 [13 14 15]
 [16 17 18]]

First Row of Second Matrix
[10 11 12]


In [75]:
# Negative Indexing
array = np.array([10,20,30,40,50,60,70,80,90,100])
print("Last Element")
print(array[-1])
print()
print("Last Three Elements")
print(array[-3:])
print()
print("Third Last Element")
print(array[-3])

Last Element
100

Last Three Elements
[ 80  90 100]

Third Last Element
80


In [77]:
# Fancy Indexing
array = np.array([11,22,33,44,55,66,77,88,99])
print("Even Position Indices")
print(array[[0,2,4,6,8]])
print()
print("Odd Position Indices")
print(array[[1,3,5,7]])

Even Position Indices
[11 33 55 77 99]

Odd Position Indices
[22 44 66 88]


In [79]:
# Boolean Indexing
array = np.arange(1,21)
print("Even Numbers")
print(array[array % 2 == 0])
print()
print("Odd Numbers")
print(array[array % 2 != 0])

Even Numbers
[ 2  4  6  8 10 12 14 16 18 20]

Odd Numbers
[ 1  3  5  7  9 11 13 15 17 19]


In [81]:
# Random Numbers Filtering
array = np.random.randint(1,101,20)
print(array)
print()
print("Numbers Greater Than 50")
print(array[array > 50])
print()
print("Numbers Less Than 25")
print(array[array < 25])

[78 51 48 82 25 31 92 97 46 81 18 69  7 11 51 97 32 26 73 21]

Numbers Greater Than 50
[78 51 82 92 97 81 69 51 97 73]

Numbers Less Than 25
[18  7 11 21]


In [83]:
# Random Matrix Filtering
array = np.random.randint(1,101,(5,5))
print(array)
print()
print("Values Greater Than 70")
print(array[array > 70])
print()
print("Values Less Than 30")
print(array[array < 30])

[[ 6  4 19 87 56]
 [32 64 20 44 78]
 [ 3 81 27 55 32]
 [51 87 11 50 45]
 [11 71 91 54 87]]

Values Greater Than 70
[87 78 81 87 71 91 87]

Values Less Than 30
[ 6  4 19 20  3 27 11 11]


In [ ]:
# Matrix Challenge
Create a 6×6 matrix containing numbers from 1 to 36 and print:
 - First row
 - Last row
 - First column
 - Last column
 - Middle 2×2 matrix
 - Reverse the entire matrix (using slicing)
This version focuses only on indexing and slicing, without introducing np.diag() or mixing in boolean

In [90]:
# Solution
array = np.arange(1, 37).reshape(6, 6)
print("Original Matrix")
print(array)
print()
print("First Row")
print(array[0])
print()
print("Last Row")
print(array[-1])
print()
print("First Column")
print(array[:, 0])
print()
print("Last Column")
print(array[:, -1])
print()
print("Middle 2 x 2 Matrix")
print(array[2:4, 2:4])
print()
print("Reverse the Entire Matrix")
print(array[::-1, ::-1])

Original Matrix
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

First Row
[1 2 3 4 5 6]

Last Row
[31 32 33 34 35 36]

First Column
[ 1  7 13 19 25 31]

Last Column
[ 6 12 18 24 30 36]

Middle 2 x 2 Matrix
[[15 16]
 [21 22]]

Reverse the Entire Matrix
[[36 35 34 33 32 31]
 [30 29 28 27 26 25]
 [24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


### Advanced Level Numpy Library Exploring

In [112]:
# Reshape
array = np.arange(1,13)
print("Original Array")
print(array)
print()
new_array = array.reshape(3,4)
print("3 x 4 Matrix")
print(new_array)

Original Array
[ 1  2  3  4  5  6  7  8  9 10 11 12]

3 x 4 Matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [116]:
# Reshape Again
array = np.arange(1,13)
new_array = array.reshape(2,6)
print("2 x 6 Matrix")
print(new_array)

2 x 6 Matrix
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [132]:
# copy() creates a separate array, so it does not change
array = np.array([10,20,30,40,50])
copy_array = array.copy()
array[0] = 100
print("Original Array")
print(array)
print()
print("Copy Array")
print(copy_array)

Original Array
[100  20  30  40  50]

Copy Array
[10 20 30 40 50]


In [134]:
# view() shares the same data, so it changes
array = np.array([10,20,30,40,50])
view_array = array.view()
array[0] = 100
print("Original Array")
print(array)
print()
print("View Array")
print(view_array)

Original Array
[100  20  30  40  50]

View Array
[100  20  30  40  50]


In [136]:
# Flatten converts a multi-dimensional array into a 1D array by creating a new copy of the original array
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Original Matrix")
print(array)
print()
new_array = array.flatten()
print("Flatten Array")
print(new_array)

Original Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatten Array
[1 2 3 4 5 6 7 8 9]


In [138]:
# Ravel converts a multi-dimensional array into a 1D array by creating a view of the original array whenever possible
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Original Matrix")
print(array)
print()
new_array = array.ravel()
print("Ravel Array")
print(new_array)

Original Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Ravel Array
[1 2 3 4 5 6 7 8 9]


In [142]:
# Broadcasting is that automatically performs operations between an array and a single value without using loops
array = np.array([10,20,30,40,50])
new_array = array * 2
print("Original Array")
print(array)
print()
print("After Multiplying by 2")
print(new_array)

Original Array
[10 20 30 40 50]

After Multiplying by 2
[ 20  40  60  80 100]


In [144]:
# Universal Function(ufunc) that performs operations element-wise on every element of an array
array = np.array([1,4,9,16,25])
print("Square Root")
print(np.sqrt(array))
print()
print("Square")
print(np.square(array))
print()
print("Absolute Value")
print(np.abs(array))

Square Root
[1. 2. 3. 4. 5.]

Square
[  1  16  81 256 625]

Absolute Value
[ 1  4  9 16 25]


In [146]:
# More Universal functions
array = np.array([1,2,3,4,5])
print("Original Array")
print(array)
print()
print("Exponential")
print(np.exp(array))
print()
print("Natural Log")
print(np.log(array))
print()
print("Sine")
print(np.sin(array))
print()
print("Cosine")
print(np.cos(array))

Original Array
[1 2 3 4 5]

Exponential
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Natural Log
[0.         0.69314718 1.09861229 1.38629436 1.60943791]

Sine
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Cosine
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [148]:
# Generate and Sort Random Numbers
array = np.random.randint(1,101,10)
print("Original Array")
print(array)
print()
sorted_array = np.sort(array)
print("Sorted Array")
print(sorted_array)

Original Array
[90 51 66 91 68 20 80 22 20 61]

Sorted Array
[20 20 22 51 61 66 68 80 90 91]


In [150]:
# Mean & Median
array = np.random.randint(1,101,20)
print("Random Numbers")
print(array)
print()
print("Mean =", np.mean(array))
print("Median =", np.median(array))

Random Numbers
[24 87 32 67 30 51 82 26 27 51 71 57 90 55 75 57 63 71 27 31]

Mean = 53.7
Median = 56.0


In [152]:
# Maximum and Index of Maximum
array = np.random.randint(1,101,20)
print("Random Numbers")
print(array)
print()
print("Maximum Value =", np.max(array))
print("Index of Maximum =", np.argmax(array))

Random Numbers
[15 71 15 92 74  6 26 82 98 97 80 46 62 14 41 74 78 26 70 56]

Maximum Value = 98
Index of Maximum = 8


In [154]:
# shuffle() randomly rearranges the elements of an array in place (it changes the original array)
array = np.arange(1,21)
print("Before Shuffle")
print(array)
np.random.shuffle(array)
print()
print("After Shuffle")
print(array)

Before Shuffle
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

After Shuffle
[19 13  2 18  8 15 11  7 20  4 10 14  1  9 16 12  6  5 17  3]


In [156]:
# seed() makes random numbers reproducible by generating the same sequence each time
np.random.seed(42)
array1 = np.random.randint(1,101,10)
np.random.seed(42)
array2 = np.random.randint(1,101,10)
print("First Array")
print(array1)
print()
print("Second Array")
print(array2)

First Array
[52 93 15 72 61 21 83 87 75 75]

Second Array
[52 93 15 72 61 21 83 87 75 75]


In [158]:
# Concatenate Two Arrays
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
new_array = np.concatenate((array1,array2))
print("First Array")
print(array1)
print()
print("Second Array")
print(array2)
print()
print("Joined Array")
print(new_array)

First Array
[1 2 3]

Second Array
[4 5 6]

Joined Array
[1 2 3 4 5 6]


In [160]:
# Split an Array
array = np.arange(1,21)
print("Original Array")
print(array)
print()
new_array = np.split(array,4)
print("Split into 4 Parts")
for part in new_array:
    print(part)

Original Array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Split into 4 Parts
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


In [162]:
# Statistics
array = np.random.randint(1,101,20)
print("Random Numbers")
print(array)
print()
print("Median =", np.median(array))
print("Standard Deviation =", np.std(array))
print("Variance =", np.var(array))
print("Index of Maximum =", np.argmax(array))
print("Index of Minimum =", np.argmin(array))

Random Numbers
[ 88 100  24   3  22  53   2  88  30  38   2  64  60  21  33  76  58  22
  89  49]

Median = 43.5
Standard Deviation = 30.31979551382232
Variance = 919.2900000000002
Index of Maximum = 1
Index of Minimum = 6


In [164]:
# Random Module
fruits = ["Apple","Mango","Banana","Orange","Grapes"]
print("10 Random Integers")
print(np.random.randint(1,101,10))
print()
print("10 Random Floating Numbers")
print(np.random.rand(10))
print()
print("5 Random Fruits")
print(np.random.choice(fruits,5))

10 Random Integers
[91 59 42 92 60 80 15 62 62 47]

10 Random Floating Numbers
[0.61838601 0.38246199 0.98323089 0.46676289 0.85994041 0.68030754
 0.45049925 0.01326496 0.94220176 0.56328822]

5 Random Fruits
['Mango' 'Apple' 'Mango' 'Grapes' 'Mango']
